---
apiVersion: v1
kind: Secret
metadata:
  name: secret-db
  labels:
    name: secret-db
type: Opaque
data:
  ROOT_PASSWORD: cm9vdHJvb3Q=
  PASSWORD: cGFzc3dvcmQrKw==
  USER: d3A=
  DATABASE: d3A=
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-wp
  labels:
    name: secret-wp
type: Opaque
data:
  WORDPRESS_DB_PASSWORD: cm9vdHJvb3Q=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-wp
data:
  WORDPRESS_DB_HOST: cluster-db-mysql-master.wp.svc.cluster.local
  WORDPRESS_DB_USER: root
  WORDPRESS_DB_NAME: wp