apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing-wp
  labels:
    name: ing-wp
    env: dev
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: svc-wp-app
            port: 
              name: ext-port-wp-app
