apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-wp-app
  labels:
    name: pvc-wp-app
    env: dev
spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
