---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-bggapp
  labels:
    name: deploy-bggapp
    env: dev
spec:
  replicas: 3
  selector: 
    matchLabels:
      name: pod-bggapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0 
  template:
    metadata:
      name: pod-bggapp
      labels:
        name: pod-bggapp
        env: dev
      namespace: bggns
    spec:
      containers:
        - name: container-bggapp
          image: stackupiss/bgg-backend:v2
          imagePullPolicy: IfNotPresent
          ports:
            - name: port-bggapp
              containerPort: 3000
          envFrom:
            - configMapRef:
                name: cm-bgg
            - secretRef:
                name: secret-bgg

---
apiVersion: v1
kind: Service
metadata:
  name: svc-bggapp
  labels:
    name: svc-bggapp
    env: dev
spec:
  type: LoadBalancer
  selector:
    name: pod-bggapp
  ports:
    - port: 8080
      targetPort: port-bggapp