---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-bgg
  labels:
    name: cm-bgg
    env: dev
data:
  BGG_DB_USER: root
  BGG_DB_HOST: svc-bggdb.bggns2.svc.cluster.local

---
apiVersion: v1
kind: Secret
metadata:
  name: secret-bgg
  labels:
    name: secret-bgg
    env: dev
data:
  BGG_DB_PASSWORD: Y2hhbmdlaXQ=
