apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-bggdb
  labels:
    name: pvc-bggdb
    env: dev
spec:
  resources:
    requests:
      storage: 2Gi
  storageClassName: do-block-storage
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
